### ISSUE TITLE
Way to not print whitespace in htmlTemplate

### ISSUE THREAD

**Issue by jcubic** [rstudio/htmltools#153] opened 2020-01-15 19:02 UTC
There is one more whitespace issue, this is continuation of #19 

This is the case:

```html
<script>
var id = '{{ id }}';
// ... other code
</script>
```

and

```R
htmlTemplate("file.RHtml", id = generateId())
```

You can use toJSON like with any structure, but it would be nice to have a way to insert value inline. There may be other usecases that this would be needed, like list of inline things that need to be side by side and need to be in two differnent template variable like:

```R
htmlTemplate("file.RHtml", a = tags$span("foo"), b = tags$span("bar"))
```

```html
<ul><li>{{ a }}</li><li>{{ b }}</li></ul>
```
this may be needed to remove any extra whitespace, that can cause CSS layout issues (spaces between elements).

This probably can be handled with #57.

**Comment by jcheng5** [comment] 2020-01-15 22:51
Thanks! I'm going to close this as a dupe of #57, but a fix is inbound.

**Closed by jcheng5** 2020-01-15 22:51 UTC
