### ISSUE TITLE
tagWrite has a condition length > 1

### ISSUE THREAD

**Issue by llrs** [rstudio/htmltools#275] opened 2021-06-15 08:29 UTC
I was using Rstudio (1.4.1717) on visual mode and used the command palette to insert a citation when I noted this error on the console:

```
<environment: namespace:htmltools>
 --- function search by body ---
Function tagWrite in namespace htmltools has this body.
 ----------- END OF FAILURE REPORT -------------- 
Warning: Error in if: the condition has length > 1
  104: tagWrite
  103: tagWrite
  102: tagWrite
  101: doRenderTags
  100: processDeps
   99: transform
   98: func
   96: f
   95: Reduce
   86: do
   85: hybrid_chain
   84: renderFunc
   83: output$bib_file
    3: shiny::runApp
    2: runGadget
    1: citr:::insert_citation
```

This is due to having these environmental variables on my .Renviron:
```
_R_CHECK_LENGTH_1_CONDITION_ =${_R_CHECK_LENGTH_1_CONDITION_-verbose}
_R_CHECK_LENGTH_1_LOGIC2_=${_R_CHECK_LENGTH_1_LOGIC2_-verbose}
```

I'm using R 3.6.3 and htmltools version 0.5.1.1 (from CRAN) and citr 0.3.2 from when it was on CRAN.

**Comment by cpsievert** [comment] 2021-06-15 14:09
This is most likely an issue with `{citr}` so you might want to file an issue on their issue tracker

**Comment by llrs** [comment] 2021-06-16 07:21
Sorry the traceback mentions htmltools namespace so I opened here the issue. 
I have opened an issue there. Feel free to close this one.

**Comment by hadley** [comment] 2021-08-11 12:59
Also indirectly a duplicate of #284

**Closed by hadley** 2021-08-11 12:59 UTC
